import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import StoreProvider from "@/redux/StoreProvider";
import "../sass/base/reset.scss";
import "../sass/base/common.scss";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${poppinsSans.variable}`}>{children}</body>
      </html>
    </StoreProvider>
  );
}
